module.exports=()=>{var n=Math.floor(Math.random() * arr().length)
                    return arr()[n]}
function arr(){return [ //making arr a function so array can be defined below
'A bird in the hand is worth two in the bush',
'A dog is a man\'s best friend',
'A fish out of water',
'A fly in the ointment',
'A leopard cannot change its spots',
'A pig in a poke',
'A woman needs a man like a fish needs a bicycle',
'An albatross around one\'s neck',
'Busy as a bee',
'Happy as a clam',
'Snug as a bug in a rug',
'As the crow flies',
'Barking up the wrong tree',
'Bats in the belfry',
'A bee in your bonnet',
'Beetle-browed',
'To bell the cat',
'Birds of a feather flock together',
'Black sheep of the family',
'Cat got your tongue?',
'Chew the cud',
'Cold enough to freeze the balls off a brass monkey',
'Counting sheep',
'Crocodile tears',
'Curiosity killed the cat',
'Don\'t count your chickens before they\'re hatched',
'A fly on the wall',
'Get off your high horse',
'Go the whole hog',
'Hobby-horse',
'Hold your horses',
'How now brown cow?',
'Hush puppies',
'In a pig\'s eye',
'In the doghouse',
'Kangaroo court',
'Lame duck',
'Let the cat out of the bag',
'Like a moth to a flame',
'Make a bee-line',
'Never look a gift horse in the mouth',
'Night owl',
'Paper tiger',
'Casting pearls before swine',
'Pony up',
'Pop goes the weasel',
'Putting the cart before the horse',
'Raining cats and dogs',
'Red herring',
'Sacred cow',
'Stool pigeon',
'Straight from the horse\'s mouth',
'Swan song',
'The bee\'s knees',
'The best laid schemes of mice and men',
'The birds and the bees',
'The chickens have come home to roost',
'The early bird catches the worm',
'The elephant in the corner',
'The tail wagging the dog',
'Till the cows come home',
'Top dog',
'Weasel words',
'When pigs fly',
'Wild goose chase',
'You can lead a horse to water, but you can\'t make it drink',
'You can\'t teach an old dog new tricks']}
